"""Graded extracts for G36. The hidden ones never exist in the agent's environment.

Every extract keeps the documented mechanisms - a stable weather-load relationship that a tariff
cannot change, a voluntary pilot randomised inside the opt-in group, and a tariff response that
fades as cooling demand rises. Only the operating regime moves.

The HISTORICAL period is generated by identical parameters in every extract: base, beta, the
historical weather distribution and the noise are untouched. Historical fit and backtest are
therefore statistically indistinguishable across extracts, while the correct target forecast
differs. A backtest cannot separate them; only the pilot can.

SE_REF holds, per extract and graded quantity, the reference standard error: the RMSE of the
accepted estimator families over Monte-Carlo redraws of the same design
(tools/g36/fixture_audit.py). Tolerance = TOL_MULTIPLIER x SE_REF.
"""
import copy

from world import VISIBLE_SPEC


def _spec(**over):
    s = copy.deepcopy(VISIBLE_SPEC)
    for k, v in over.items():
        s[k] = v
    return s


# Response magnitudes are an EVEN sweep of the published time-of-use peak-reduction range:
# maximum per-segment reductions of 10 %, 14 % (visible), 23 % and 30 %. They were chosen as a
# representative sample of that literature, not by inspecting which side of the capacity ceiling
# each one lands on. See research/g36/threshold_provenance.md.
_BASE = (0.035, 0.070, 0.165, 0.205)          # the unscaled per-segment response


def _resp(scale):
    return tuple(round(r * scale, 6) for r in _BASE)


HIDDEN_SPECS = [
    # A: minimal response AND a badly skewed opt-in group. Selection transport bites hardest here:
    #    the volunteers look far more responsive than the estate they are meant to represent.
    _spec(name="hidden_a", seed=36200431, n_households=5600,
          resp0=_resp(0.50), optin_prop=(0.01, 0.03, 0.22, 0.30)),
    # B and C are the discriminating pair. Identical response magnitude, identical history
    #    generation, identical enrolment behaviour. They differ ONLY in what heat does to the
    #    response: in B it is essentially unchanged (ratio 0.96 between target and pilot weather),
    #    in C it quarters (ratio 0.25). Opposite procurement decisions follow.
    _spec(name="hidden_b", seed=36300557, n_households=6400,
          resp0=_resp(1.45), heat_damping=0.10),
    _spec(name="hidden_c", seed=36400683, n_households=5800,
          resp0=_resp(1.45), heat_damping=2.70),
    # D: the middle of the published range with a moderate heat fade.
    _spec(name="hidden_d", seed=36500809, n_households=6200,
          resp0=_resp(1.10)),
]


def by_name(name):
    if name == "visible":
        return copy.deepcopy(VISIBLE_SPEC)
    for s in HIDDEN_SPECS:
        if s["name"] == name:
            return copy.deepcopy(s)
    raise KeyError(name)


ALL_NAMES = ["visible"] + [s["name"] for s in HIDDEN_SPECS]

QUANT = ("target_peak_kw", "estate_tou_response_at_target_cdd")

# filled in by tools/g36/fixture_audit.py
SE_REF = {
    'visible': {
        'target_peak_kw': 0.01935224,
        'estate_tou_response_at_target_cdd': 0.00690462,
    },
    'hidden_a': {
        'target_peak_kw': 0.02753497,
        'estate_tou_response_at_target_cdd': 0.01122151,
    },
    'hidden_b': {
        'target_peak_kw': 0.01782090,
        'estate_tou_response_at_target_cdd': 0.00584113,
    },
    'hidden_c': {
        'target_peak_kw': 0.03985938,
        'estate_tou_response_at_target_cdd': 0.01650186,
    },
    'hidden_d': {
        'target_peak_kw': 0.01693889,
        'estate_tou_response_at_target_cdd': 0.00617804,
    },
}
SE_REF_REDRAWS = 30

# Tolerance = TOL_MULTIPLIER x SE_REF, chosen from a MEASURED window after the K9 gate confirmed
# that three genuinely independent estimator families agree (tools/g36/tolerance_calibration.py).
#
#   lower bound  0.91 SE_REF  - the worst error of any legitimate route across all fixtures
#   upper bound  6.88 SE_REF  - the smallest "most detectable" error among wrong analyses
#
# 2.5 sits near the geometric centre: the worst legitimate route lands at 0.36 of tolerance and the
# hardest wrong analysis is caught at 2.75x tolerance. Never inherited from another task, and never
# calibrated against a target model - no model has seen this task.
TOL_MULTIPLIER = 2.5

# v1.1: the estate response is graded under the corrected (load-weighted) definition and carries its
# own multiplier, chosen by the same measured-window procedure (research/g36/v1_1/tolerance_calibration.md).
# The forecast keeps TOL_MULTIPLIER above, unchanged from v1.
TOL_MULTIPLIER_BY_QUANT = {"estate_tou_response_at_target_cdd": None}   # set after calibration
