"""G36 remaining gates: same-history/different-future, coherent-wrong, cheap solves, leakage,
recognition-vs-execution quantification, and the F2 runner-up comparison.

Research/dev only. No model call, no container, no network.
    python research/g36/gates.py
"""
from __future__ import annotations

import sys
from dataclasses import dataclass, replace
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from simulation import (REGIMES, SpecF1, estimators_f1, truth_f1, world_f1,   # noqa: E402
                        _fit_stable, _seg_shares)


# ----------------------------------------------------------------- same history / different future
def historical_metrics(w):
    """Fit the historical model on summers 1-2 and score it on summer 3. This is the backtest a
    professional team would run, and it is the number that makes a wrong analysis look safe."""
    seg = w["seg"]
    train, test = w["hist"][:-1], w["hist"][-1]
    coef = {}
    for s in range(4):
        m = seg == s
        xs, ys = [], []
        for h in train:
            xs.append(np.repeat(h["cdd"], m.sum()))
            ys.append(h["load"][m].T.ravel())
        x = np.concatenate(xs); y = np.concatenate(ys)
        A = np.column_stack([np.ones_like(x), x])
        coef[s] = np.linalg.lstsq(A, y, rcond=None)[0]
    errs, ys = [], []
    for s in range(4):
        m = seg == s
        a, b = coef[s]
        pred = a + b * test["cdd"][None, :]
        errs.append((test["load"][m] - pred).ravel())
        ys.append(test["load"][m].ravel())
    e = np.concatenate(errs); y = np.concatenate(ys)
    rmse = float(np.sqrt(np.mean(e ** 2)))
    r2 = float(1 - np.mean(e ** 2) / np.var(y))
    return dict(holdout_rmse=rmse, holdout_r2=r2, mean_hist_load=float(
        np.mean([h["load"].mean() for h in w["hist"]])))


# --------------------------------------------------------------------------------- cheap solves
def cheap_solves(w, e, t):
    sp = w["spec"]
    hist_mean = float(np.mean([h["load"].mean() for h in w["hist"]]))
    out = {
        "C1_historical_model_output": e["W1_historical_only"],
        "C3_last_value": float(w["hist"][-1]["load"].mean()),
        "C4_seasonal_naive": hist_mean,
        "C6_historical_mean": hist_mean,
        "C7_pilot_mean": float(w["pilot_load"][w["tou"]].mean()),
        "C9_constant_procure": 1e9,
        "C10_constant_defer": -1e9,
        "C11_largest_segment_only": None,
        "C13_latest_period": float(w["hist"][-1]["load"].mean()),
        "C15_intervention_flag": None,
        "C17_aggregate_pre_post": None,
        "C24_linear_extrapolation": None,
    }
    # largest segment only: forecast built from the single biggest segment
    stable = _fit_stable(w)
    big = int(np.argmax(_seg_shares(w)))
    a, b = stable[big]
    out["C11_largest_segment_only"] = float(np.mean(a + b * w["cdd_target"]))
    # intervention flag: historical mean scaled by a flat "policy will cut 10%" rule of thumb
    out["C15_intervention_flag"] = hist_mean * 0.90
    # aggregate pre/post inside the pilot, applied to the historical level
    pre = float(w["pilot_load"][w["optin"] & ~w["tou"]].mean())
    post = float(w["pilot_load"][w["tou"]].mean())
    out["C17_aggregate_pre_post"] = hist_mean * (post / pre)
    # naive linear extrapolation of the historical summer means
    means = [h["load"].mean() for h in w["hist"]]
    slope = (means[-1] - means[0]) / max(len(means) - 1, 1)
    out["C24_linear_extrapolation"] = float(means[-1] + slope)
    return out


# --------------------------------------------------------------------- recognition vs execution
HINTS = {
    "H0_no_hint": ["W1_historical_only", "W2_retrain_latest_window", "W15_seasonal_naive"],
    "H1_response_does_not_transport_from_pilot": ["W8_selection_fixed_only"],
    "H2_response_depends_on_temperature": ["W9_temperature_fixed_only"],
    "H1+H2_both_insights": ["V1_decompose_transport_both"],
}


def main():
    rows = []
    for sp in REGIMES:
        w = world_f1(sp)
        t = truth_f1(w, n_mc=8)
        e = estimators_f1(w)
        rows.append((sp, w, t, e))
    names = [r[0].name for r in rows]

    print("=" * 104)
    print("SAME-HISTORY / DIFFERENT-FUTURE GATE")
    print("=" * 104)
    print("The historical period is generated by identical parameters in every regime. A backtest")
    print("cannot distinguish them; only the pilot can.")
    print("\n%-28s %12s %12s %14s %12s %10s" % (
        "regime", "holdout_RMSE", "holdout_R2", "mean_hist_load", "TRUTH", "decision"))
    for sp, w, t, e in rows:
        h = historical_metrics(w)
        print("%-28s %12.4f %12.4f %14.4f %12.4f %10s" % (
            sp.name, h["holdout_rmse"], h["holdout_r2"], h["mean_hist_load"],
            t["target_peak_mean"], t["decision"]))
    print("\nThe discriminating pair is hidden_b_flat_in_heat and hidden_c_fades_in_heat:")
    b = [r for r in rows if r[0].name.startswith("hidden_b")][0]
    c = [r for r in rows if r[0].name.startswith("hidden_c")][0]
    hb, hc = historical_metrics(b[1]), historical_metrics(c[1])
    print("   identical response magnitude, identical history generation")
    print("   holdout RMSE  %.4f vs %.4f   (difference %.4f)" % (
        hb["holdout_rmse"], hc["holdout_rmse"], abs(hb["holdout_rmse"] - hc["holdout_rmse"])))
    print("   TRUTH         %.4f vs %.4f   -> %s vs %s" % (
        b[2]["target_peak_mean"], c[2]["target_peak_mean"], b[2]["decision"], c[2]["decision"]))

    print()
    print("=" * 104)
    print("RECOGNITION-VS-EXECUTION GATE  (the gate G35 failed)")
    print("=" * 104)
    valid_sd = 0.0142     # measured: sampling sd of the accepted estimator
    print("Each row hands the analyst an insight FOR FREE and reports the best analysis that")
    print("insight alone supports. Errors in units of the accepted estimator's sampling sd (%.4f).\n"
          % valid_sd)
    print("%-44s %s  %s" % ("insight given away", "".join("%11s" % n[:10] for n in names), "worst"))
    for hint, keys in HINTS.items():
        best_per_regime = []
        for i, (sp, w, t, e) in enumerate(rows):
            errs = [abs(e[k] - t["target_peak_mean"]) for k in keys if k in e]
            best_per_regime.append(min(errs))
        worst = max(best_per_regime)
        line = "".join("%11.1f" % (v / valid_sd) for v in best_per_regime)
        print("%-44s %s  %5.1f sd" % (hint, line, worst / valid_sd))
    print("\nwrong DECISIONS remaining after each insight:")
    for hint, keys in HINTS.items():
        bad = 0
        for sp, w, t, e in rows:
            k = keys[0]
            d = "procure" if e[k] >= sp.capacity_gate else "defer"
            if d != t["decision"]:
                bad += 1
        print("   %-44s %d / %d regimes wrong" % (hint, bad, len(rows)))

    print()
    print("=" * 104)
    print("COHERENT-BUT-WRONG GATE")
    print("=" * 104)
    print("W1_historical_only IS the incumbent model. Its backtest is excellent by construction;")
    print("it reconciles, calibrates and validates perfectly on every historical summer, and it is")
    print("wrong about the future because the mechanism it omits did not exist in the past.\n")
    print("%-28s %12s %12s %12s %12s" % ("regime", "holdout_R2", "forecast", "truth", "error"))
    for sp, w, t, e in rows:
        h = historical_metrics(w)
        print("%-28s %12.4f %12.4f %12.4f %12.4f" % (
            sp.name, h["holdout_r2"], e["W1_historical_only"], t["target_peak_mean"],
            e["W1_historical_only"] - t["target_peak_mean"]))

    print()
    print("=" * 104)
    print("CHEAP-SOLVE PANEL")
    print("=" * 104)
    cs = [cheap_solves(w, e, t) for sp, w, t, e in rows]
    print("%-32s %s   %s" % ("shortcut", "".join("%11s" % n[:10] for n in names), "decisions"))
    for k in cs[0]:
        line, right = "", 0
        for i, (sp, w, t, e) in enumerate(rows):
            v = cs[i][k]
            d = "procure" if v >= sp.capacity_gate else "defer"
            if d == t["decision"]:
                right += 1
            line += "%11.3f" % (v if abs(v) < 1e8 else np.nan)
        print("%-32s %s   %d/5" % (k, line, right))
    print("\n   truth decisions: %s" % " ".join(t["decision"][:1] for sp, w, t, e in rows))

    print()
    print("=" * 104)
    print("REPRESENTATION-LEAKAGE PROBES")
    print("=" * 104)
    for sp, w, t, e in rows:
        seg = w["seg"]
        r_opt = np.corrcoef(seg, w["optin"].astype(float))[0, 1]
        r_idx = np.corrcoef(np.arange(len(seg)), seg.astype(float))[0, 1]
        print("%-28s corr(segment, optin)=%+.3f   corr(row order, segment)=%+.3f   n_optin=%d"
              % (sp.name, r_opt, r_idx, int(w["optin"].sum())))
    print("\n   corr(segment, optin) is SUPPOSED to be non-zero - that is the selection the task is")
    print("   about, and it is visible to the analyst by design. It is experimental metadata, not")
    print("   answer leakage: knowing who opted in does not give the target forecast.")


if __name__ == "__main__":
    main()
