#!/usr/bin/env python3
"""Generate report/TRIALS.md and report/VALIDATION.md from report/data/results.json and raw jobs/ (read-only)."""
import glob, json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
R = json.load(open(os.path.join(ROOT, "report", "data", "results.json")))
cfg = json.load(open(os.path.join(ROOT, "scripts", "final_tasks.json")))


def result_rows(path):
    out = []
    for p in glob.glob(os.path.join(ROOT, "jobs", "*", "*", "result.json")):
        r = json.load(open(p))
        if (r.get("config", {}).get("task", {}) or {}).get("path") == path:
            out.append((p.split(os.sep)[-3], r))
    return out


T = ["# Appendix C — trial IDs, invalid runs and costs", "",
     "Generated by `scripts/write_appendices.py` from raw Harbor `result.json` files.", "",
     "## Final suite: counted trials", "", "| task | job | trial | reward | cost (USD) | task checksum |", "|---|---|---|---|---|---|"]
for tid in R["final"]:
    for t in R["pilot"][tid]["trials"]:
        T.append(f"| {tid} | {t['job']} | {t['trial']} | {t['reward']} | {t['cost_usd']:.4f} | {t['checksum']} |")
fs = R["final_summary"]
T += ["", f"**Final suite:** {fs['successful_trials']} / {fs['trials']} successful trials; "
      f"{fs['tasks_with_pass3']} / {fs['tasks']} tasks with pass@3 = 1 ({100 * fs['task_pass_at_3']:.0f} %).", "",
      "## Invalid runs (not counted)", ""]
for tr, why in cfg.get("invalid_trials", {}).items():
    T.append(f"- `{tr}`: {why}")
T += ["- Task01 and G08 had infrastructure-invalid jobs (API-key / free-tier quota; agent-setup timeout), recorded under "
      "job names containing `INVALID`. Neither task is in the final suite.", "",
      "## Full pilot pool (all measured tasks)", "", "| task | name | successes / valid trials | pass@3 | invalid runs | model cost (USD, incl. invalid) |",
      "|---|---|---|---|---|---|"]
for tid, t in R["pilot"].items():
    T.append(f"| {tid} | {t['name']} | {t['successes']} / {t['n_valid']} | {t['pass_at_3']} | {t['invalid_runs']} | {t['model_cost_usd']:.4f} |")
c = R["costs"]
T += ["", "## Cost accounting", "",
      f"- Gemini 3 Flash, all runs on the 12 pilot tasks (incl. invalid): ${c['gemini_all_runs_usd']:.2f}",
      f"- Gemini 3 Flash, excluded G36 baseline: ${c['gemini_excluded_g36_usd']:.2f}",
      f"- Gemini 3 Flash, Task02 explicit-invariant ablation: ${c['gemini_task02_ablation_usd']:.2f}",
      f"- `harbor check` evaluator runs (claude-code): ${c['harbor_check_usd']:.2f}",
      f"- Final-suite counted trials: ${sum(t['cost_usd'] for tid in R['final'] for t in R['pilot'][tid]['trials']):.2f}"]
open(os.path.join(ROOT, "report", "TRIALS.md"), "w").write("\n".join(T) + "\n")

V = ["# Appendix B — validation evidence", "", "Generated by `scripts/write_appendices.py` from raw Harbor outputs.", "",
     "## Oracle / Nop on the frozen task checksum", "", "| task | frozen checksum (trials) | Oracle runs on that checksum | Nop runs on that checksum |",
     "|---|---|---|---|"]
for t in cfg["tasks"]:
    rows = result_rows(t["path"])
    cs = {(r.get("task_checksum") or "")[:16] for j, r in rows if r.get("trial_name") in t["valid_trials"]}
    cs = cs.pop() if len(cs) == 1 else "MISMATCH"
    def fmt(agent):
        v = [f"{j}: {((r.get('verifier_result') or {}).get('rewards') or {}).get('reward')}" for j, r in rows
             if (r.get("agent_info") or {}).get("name") == agent and (r.get("task_checksum") or "")[:16] == cs]
        return "; ".join(sorted(v)) or "—"
    V.append(f"| {t['id']} | {cs} | {fmt('oracle')} | {fmt('nop')} |")
V += ["", "## harbor check", ""]
for t in cfg["tasks"]:
    name = os.path.basename(t["path"])
    for p in sorted(glob.glob(os.path.join(ROOT, "jobs", "*", "check_report.json")) + glob.glob(os.path.join(ROOT, "jobs", "*", "*", "check_report.json"))):
        r = json.load(open(p))
        for res in r.get("results", []):
            if res.get("task_name") != name:
                continue
            ch = res.get("checks", {})
            bad = {k: v.get("outcome") for k, v in ch.items() if v.get("outcome") not in ("pass", "not_applicable")}
            rub = "TB3 task-implementation rubric" if len(ch) > 15 else "Harbor default rubric"
            V.append(f"- **{t['id']}** `{p.split(os.sep)[-2] if p.split(os.sep)[-2] != 'jobs' else ''}` ({rub}): "
                     f"{len(ch)} criteria, non-pass: {bad if bad else 'none'}")
V += ["", "## Mutation / wrong-method suites (pre-baseline, in the task image with the real test.sh)", "",
      "| task | cases as expected | report |", "|---|---|---|",
      "| task02 | 21 / 21 | report/task02_validation.md |", "| g05 | 38 / 38 | report/g05_prebaseline_validation.md |",
      "| g10 | 33 / 33 | report/g10_prebaseline_validation.md |", "| g24 | 30 / 30 | report/g24_prebaseline_validation.md |",
      "| g34 | 21 / 21 | report/g34_prebaseline_validation.md |"]
open(os.path.join(ROOT, "report", "VALIDATION.md"), "w").write("\n".join(V) + "\n")
print("wrote report/TRIALS.md and report/VALIDATION.md")
